authors:
  bybatkhuu:
    name: Batkhuu Byambajav
    description: Creator, maintainer
    avatar: https://avatars.githubusercontent.com/bybatkhuu
    url: https://github.com/bybatkhuu
  sokhibjon:
    name: Baratov Sokhibjon
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/BaratovSokhibjon
    url: https://github.com/BaratovSokhibjon
  Oybek:
    name: Oybek Inokov
    description: Contributor
    avatar: https://avatars.githubusercontent.com/inokov
    url: https://github.com/inokov
