authors:
  bybatkhuu:
    name: Batkhuu Byambajav
    description: Creator, maintainer
    avatar: https://avatars.githubusercontent.com/bybatkhuu
    url: https://github.com/bybatkhuu
  sokhibjon:
    name: Baratov Sokhibjon
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/BaratovSokhibjon
    url: https://github.com/BaratovSokhibjon
  akimovsarvar:
    name: Akimov Sarvar
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/akimovsarvar
    url: https://github.com/akimovsarvar
