authors:
  bybatkhuu:
    name: Batkhuu Byambajav
    description: Creator, maintainer
    avatar: https://avatars.githubusercontent.com/bybatkhuu
    url: https://github.com/bybatkhuu
  sokhibjon:
    name: Baratov Sokhibjon
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/BaratovSokhibjon
    url: https://github.com/BaratovSokhibjon
  oybek:
    name: Oybek Inokov
    description: Contributor
    avatar: https://avatars.githubusercontent.com/inokov
    url: https://github.com/inokov
  akimovsarvar:
    name: Akimov Sarvar
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/akimovsarvar
    url: https://github.com/akimovsarvar
  abdukarimovhm:
    name: Abdukarimov Humoyunbek
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/abdukarimovhm
    url: https://github.com/abdukarimovhm
